@startuml
title Контекстная диаграмма монолитной системы
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml
' Пользователи и система
Person(user, "Пользователь", 'Пользователь приложения компании «Тёплый дом»')
Person(master, "Специалист подключения", 'Выездной специалист по подключению датчиков к приложению')
' Система
System(system, "Система «Тёплый дом»", 'Система управления умным домом')
' Внешние системы
' System_Ext(home_1, "Датчик 1", 'Датчик температуры пользователя')
' System_Ext(home_2, "Датчик 2", 'Датчик температуры пользователя')
System_Ext(home_n, "Датчик N", 'Датчик температуры пользователя')
' Отношения между элементами
Rel(user, system, "Регулирует температуру в доме. Включает и выключает датчики")
' Rel(system, home_1, "Управляет датчиком")
' Rel(system, home_2, "Регистрирует датчик")
Rel(system, home_n, "Регистрирует датчик. Управляет датчиком")
' Rel(master, home_1, "Подключает датчики к системе")
' Rel(master, home_2, "")
Rel(master, home_n, "Подключает датчики к системе")
' Подсказка для расположения
' home_1 -[hidden]down-> master
' home_2 -[hidden]down-> master
' home_n -[hidden]down-> master
@enduml 