@startuml
title Контейнерная диаграмма системы
' Импорт
!includeurl ../../uml-lib/C4_Container.puml
' Пользователи
Person(user, "Пользователь", 'Пользователь приложения компании «Тёплый дом»')
LAYOUT_TOP_DOWN()
' Система
Container_Boundary(system, "Система «Тёплый дом»") {
' Мобильное, веб приложения и API Gateway
  together {
    Container(WebApp, "Веб приложение", "React, TypeScript", "Управляет взаимодействием с пользователем")
    Container(MobileApp, "Мобильное приложение", "Kotlin, Swift", "Управляет взаимодействием с пользователем")
  }
  together {
    Container(ApiGateway, "API Gateway", "NGINX", "Обрабатывает входящие запросы и маршрутизирует их к соответствующим сервисам")
    Container(MediaServer, "Media Server", "MediaMTX", "Получает, преобразует и передаёт видеопотоки камер")
  }


  together {
    ' Сервисы приложения
    Container(DeviceService, "Device Service", "Go", "Реализует функциональность управления устройствами")
    Container(NotificationService, "Notification Service", "Go", "Обеспечивает функциональность уведомлений")
    Container(UserService, "User Service", "Go", "Реализует функциональность управления пользователями")
    Container(ScenarioService, "Scenario Service", "Go", "Реализует функциональность управления сценариями действий и уведомлений, как пользовательскими, так и шаблонными")
    ' СУБД
    ContainerDb(UserDatabase, "User\nDatabase", "PostgreSQL", "Хранит данные\nпользователей")
    ContainerDb(DeviceDatabase, "Device\nDatabase", "PostgreSQL", "Хранит данные\nустройств")
    ContainerDb(ScenarioDatabase, "Scenario\nDatabase", "PostgreSQL", "Хранит данные\nсценариев")
    ContainerDb(NotificationDatabase, "Notification\nDatabase", "PostgreSQL", "Хранит данные\nуведомлений")
  }
' Брокеры сообщений
  Container(MqttBroker, "MQTT Broker", "Mosquitto", "Обеспечивает обмен сообщениями между устройствами и сервисами приложения")
  Container(Kafka, "Apache Kafka", "Kafka", "Обеспечивает обмен сообщениями между сервисами приложения")
}
' Внешние системы
System_Ext(home, "Дом N", 'Дом пользователя')
' Взаимодействия пользователя
user ..> WebApp : "Использует приложение"
user ..> MobileApp : "Использует приложение"
' Взаимодействия приложений
WebApp ..> ApiGateway : "Отправляет\nзапросы"
MobileApp ..> ApiGateway : "Отправляет\nзапросы"
' Взаимодействия ApiGateway
ApiGateway ..> DeviceService : "Пересылает запросы к сервису устройств"
ApiGateway ..> UserService : "Пересылает запросы к сервису пользователей"
ApiGateway ..> ScenarioService : "Пересылает\nзапросы к\nсервису сценариев"
ApiGateway ..> NotificationService : "Пересылает\nзапросы к\nсервису уведомлений"
' Взаимодействия сервисов с базой данных
DeviceService .right.> DeviceDatabase : "Читает\nи\nзаписывает\nданные"
UserService .right.> UserDatabase : "Читает\nи\nзаписывает\nданные"
ScenarioService .right.> ScenarioDatabase : "Читает\nи\nзаписывает\nданные"
NotificationService .right.> NotificationDatabase : "Читает\nи\nзаписывает\nданные"
' Взаимодействия сервисов
MediaServer ..> WebApp : "Передаёт видеопоток [WebRTC]"
MediaServer ..> MobileApp : "Передаёт видеопоток [WebRTC]"
DeviceService ..> MqttBroker : "Публикует и получает сообщения [MQTT]"
ScenarioService ..> MqttBroker : "Получает события и публикует команды [MQTT]"
NotificationService ..> WebApp : "Отправляет уведомления [WebSocket]"
NotificationService ..> MobileApp : "Отправляет уведомления [Push]"
' Взаимодействия MQTT брокер
MqttBroker <.> home : "Обменивается сообщениями с IoT-устройствами [MQTT]"
MediaServer ..> home : "Получает видеопотоки с камер [RTSP]"
' Взаимодействия Kafka
UserService <.> Kafka : "Публикует/получает\nсобытия"
DeviceService <.> Kafka : "Публикует/получает\nсобытия"
ScenarioService <.> Kafka : "Публикует/получает\nсобытия"
MediaServer <.> Kafka : "Публикует/получает\nсобытия"
NotificationService <.> Kafka : "Публикует/получает\nсобытия"
' Подсказка для рендера
user -[hidden]down-> MobileApp
user -[hidden]down-> ApiGateway
WebApp -[hidden]down-> ApiGateway
MobileApp -[hidden]down-> ApiGateway
ApiGateway -[hidden]down-> DeviceService
ApiGateway -[hidden]down-> UserService
ApiGateway -[hidden]down-> ScenarioService
ApiGateway -[hidden]down-> NotificationService

DeviceService -[hidden]down-> Kafka
ScenarioService -[hidden]down-> Kafka

UserService -[hidden]right-> ScenarioService

MediaServer -[hidden]up-> WebApp
MediaServer -[hidden]up-> MobileApp
@enduml