@startuml
title Контейнерная диаграмма системы
' Импорт
!includeurl ../../uml-lib/C4_Container.puml
' Пользователи
Person(user, "Пользователь", 'Пользователь приложения компании «Тёплый дом»')
' Система
Container_Boundary(system, "Система «Тёплый дом»") {
' Мобильное, веб приложения и API Gateway
  Container(WebApp, "Веб приложение", "React, TypeScript", "Управляет взаимодействием с пользователем")
  Container(MobileApp, "Мобильное приложение", "Kotlin, Swift", "Управляет взаимодействием с пользователем")
  Container(ApiGateway, "API Gateway", "NGINX", "Обрабатывает входящие запросы и маршрутизирует их к соответствующим сервисам")
' Сервисы приложения
  Container(DeviceService, "Device Service", "Go", "Реализует функциональность управления устройствами")
  Container(UserService, "User Service", "Go", "Реализует функциональность управления пользователями")
  Container(ScenarioService, "Scenario Service", "Go", "Реализует функциональность управления сценариями, как пользовательскими, так и шаблонными")
  Container(MediaServer, "Media Server", "MediaMTX", "Получает, преобразует и передаёт видеопотоки камер")
' Брокеры сообщений
  Container(MqttBroker, "MQTT Broker", "Mosquitto", "Обеспечивает обмен сообщениями между устройствами и сервисами приложения")
  Container(Kafka, "Apache Kafka", "Kafka", "Обеспечивает обмен сообщениями между сервисами приложения")
' СУБД
  ContainerDb(UserDatabase, "User Database", "PostgreSQL", "Хранит данные пользователей")
  ContainerDb(DeviceDatabase, "Device Database", "PostgreSQL", "Хранит данные устройств")
  ContainerDb(ScenarioDatabase, "Scenario Database", "PostgreSQL", "Хранит данные сценариев")
}
' Внешние системы
System_Ext(home, "Дом N", 'Дом пользователя')
' Взаимодействия пользователя
user ..> WebApp : "Использует приложение"
user ..> MobileApp : "Использует приложение"
' Взаимодействия приложений
WebApp ..> ApiGateway : "Отправляет запросы"
MobileApp ..> ApiGateway : "Отправляет запросы"
' Взаимодействия ApiGateway
ApiGateway ..> DeviceService : "Пересылает запросы к сервису устройств"
ApiGateway ..> UserService : "Пересылает запросы к сервису пользователей"
ApiGateway ..> ScenarioService : "Пересылает запросы к сервису сценариев"
' Взаимодействия сервисов с базой данных
DeviceService ..> DeviceDatabase : "Читает/Записывает данные"
UserService ..> UserDatabase : "Читает/Записывает данные"
ScenarioService ..> ScenarioDatabase : "Читает/Записывает данные"
' Взаимодействия сервисов
MediaServer ..> WebApp : "Передаёт видеопоток [WebRTC]"
MediaServer ..> MobileApp : "Передаёт видеопоток [WebRTC]"
DeviceService ..> MqttBroker : "Публикует и получает сообщения [MQTT]"
ScenarioService ..> MqttBroker : "Получает события и публикует команды [MQTT]"
' Взаимодействия MQTT брокер
MqttBroker <.> home : "Обменивается сообщениями с IoT-устройствами [MQTT]"
MediaServer ..> home : "Получает видеопотоки с камер [RTSP]"
' Взаимодействия Kafka
DeviceService <.> Kafka : "Публикует/получает события"
ScenarioService <.> Kafka : "Публикует/получает события"
MediaServer <.> Kafka : "Публикует/получает события"
' Подсказка для рендера
user -[hidden]down-> MobileApp
MobileApp -[hidden]down-> ApiGateway
WebApp -[hidden]left-> MobileApp

Kafka -[hidden]down-> DeviceService
@enduml