@startuml
title Компонентная диаграмма сервиса камер
!include ../../uml-lib/C4_Component.puml
' Сервис камер
Container_Boundary(CameraService, "Camera Service") {
' Компоненты сервиса камер
  Component(ControllerComponent, "Camera Controller","Обрабатывает HTTP-запросы и маршрутизирует их к соответствующим компонентам")
  Component(ManagerComponent, "Camera Manager", "Управляет камерами, настройками и доступом к видеопотокам")
  Component(ServiceComponent, "Camera Service", "Обрабатывает бизнес-логику, связанную с камерами")
  Component(RepositoryComponent, "Repository Layer", "Обеспечивает доступ к данным камер в базе данных")
}
' СУБД Camera Service
ContainerDb(CameraDatabase, "Camera Database", "PostgreSQL", "Хранит данные CameraService")
' Взаимодействия
ServiceComponent ..> RepositoryComponent : "Читает/Записывает данные"
RepositoryComponent ..> CameraDatabase : "Читает/Записывает данные"



@enduml